Stop Reloading
spo-iitk/ras-frontend pull request #227
Opened 2023-07-02 12:02 UTC by AshNewar

2023-07-07 06:41 UTC, abhishekshree requested changes
Good work, just don't change configs on your own bacche

2023-07-07 06:41 UTC, abhishekshree commented on .eslintrc.json
don't change the lint without a discussion

2023-07-07 06:41 UTC, abhishekshree commented on next.config.js
unnecessary

2023-08-08 21:50 UTC, utkarsh-tf141 commented
@AshNewar Resolve merge conflicts and the changes requested

2023-08-10 09:10 UTC, closed without merging