Jp dashboard
spo-iitk/ras-frontend pull request #97
Opened 2022-06-13 14:22 UTC by amdpt323

- closes #92

2022-06-14 06:48 UTC, ManasGupta1310 requested changes

2022-06-14 06:48 UTC, ManasGupta1310 commented on pages/admin/rc/[rcid]/proforma/[proformaId]/index.tsx
> +import { Button, Card, Grid, Stack, Typography } from "@mui/material";
This file already exists in main repo and I had changed its responsiveness. Please do not commit this file

2022-06-14 06:48 UTC, ManasGupta1310 commented on pages/admin/rc/index.tsx
> +  const [setRc] = useState();
Change this setRc to setRCList

2022-06-14 06:48 UTC, ManasGupta1310 commented on pages/admin/rc/index.tsx
> +      const some_var = await admin_getrc();
rename some_var to RCs

2022-06-15 10:06 UTC, 1-Harshit commented
What's going on here?

2022-06-15 19:11 UTC, 1-Harshit commented
closing, inactivity

2022-06-16 13:59 UTC, 1-Harshit commented
Closed

2022-06-16 13:59 UTC, closed without merging